export const ROLES = {
  ADMIN: "ADMIN",
  RECEPTIONIST: "RECEPTIONIST",
  EMPLOYEE: "EMPLOYEE"
};

export const VISIT_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CHECKED_IN: "CHECKED_IN",
  CHECKED_OUT: "CHECKED_OUT",
  CANCELLED: "CANCELLED"
};
